### PR TITLE
fix ifdef to use HAS_SYSCALL_TGKILL for tgkill as it was intented

### PR DESCRIPTION
**Pull request by stevenvandenbrandenstift**
Seen issue while compiling on alpine linux (musl).

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Oops, Nice catch! Thanks!

**Comment by stevenvandenbrandenstift** [comment]
I am still tracking other bugs that make the compilation fail on alpine linux. But I want to make fixes step by step.

**Comment by stevenvandenbrandenstift** [comment]
is there some place to disuss issues, eg a matrix room or similar?

**Comment by Sonicadvance1** [comment]
We have an official Discord server at https://discord.gg/fexemu

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
