### PR TITLE
ASM Tests: X87 Rounding modes

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Comment by pmatos** [comment]
I was thinking initially the Luna Nights issue #3685 was related to rounding modes but it doesn't seem likely. Still investigating that one. In the meantime I wrote a bunch of tests that might be useful to have in-tree.

**Comment by Sonicadvance1** [comment]
vixl sim doesn't support any rounding mode other than ties to even, so this will need to fall down the disabled test path for that

**Comment by pmatos** [comment]
> vixl sim doesn't support any rounding mode other than ties to even, so this will need to fall down the disabled test path for that

Makes sense.

**Comment by pmatos** [comment]
@Sonicadvance1 Is there no way to disable this just for the vixl sim path?

**Comment by Sonicadvance1** [comment]
> @Sonicadvance1 Is there no way to disable this just for the vixl sim path?

Just like in the 64-bit ASM tests path, create a `Disabled_Tests_Simulator` file and add the test.
Similar to https://github.com/FEX-Emu/FEX/blob/main/unittests/ASM/Disabled_Tests_Simulator but in the 32Bit_ASM folder.

**Comment by pmatos** [comment]
hummm, interesting, are disabled tests shown as passing? Or are the tests somehow 32bit and 64bit tests actually running and passing in vixl?

**Comment by pmatos** [comment]
> hummm, interesting, are disabled tests shown as passing? Or are the tests somehow 32bit and 64bit tests actually running and passing in vixl?

I wonder if this is a result of us returning zero in `guest_test_runner.py` for disabled tests in:
```
if (disabled_tests.get(test_name)):
    print(f"Test {test_name} is disabled")
    sys.exit(0)
```

What's confusing me is that the print line is not showing up in the logs.

**Comment by pmatos** [comment]
> > hummm, interesting, are disabled tests shown as passing? Or are the tests somehow 32bit and 64bit tests actually running and passing in vixl?
> 
> I wonder if this is a result of us returning zero in `guest_test_runner.py` for disabled tests in:
> 
> ```
> if (disabled_tests.get(test_name)):
>     print(f"Test {test_name} is disabled")
>     sys.exit(0)
> ```
> 
> What's confusing me is that the print line is not showing up in the logs.

Humm, ok, ASM tests use `testharness_runner.py`, not `guest_test_runner.py`.

**Comment by pmatos** [comment]
**Please do not merge - I want to understand what's going on here because something doesn't make sense to me yet.**

**Comment by pmatos** [comment]
OK - now I got it. Which is why I created #3896 . Ready to review.

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
