### PR TITLE
OpcodeDispatcher: Handle F16C operations

### PR DESCRIPTION
**Pull request by lioncash**
Preliminary PR, just to get CI on this. Some of the tests still need expanding.

### CODE REVIEW

**Review by Sonicadvance1 — COMMENTED** [review]
Very nice. So it looks like what's left is to write some tests for the four rounding modes? So generating some various precise 32-bit float values both positive and negative and just run through all eight rounding mode variants? 4 imm, 4 MXCSR?

**Comment by lioncash** [comment]
Yeah, expanding rounding mode coverage is the main thing left

**Comment by Sonicadvance1** [comment]
> Yeah, expanding rounding mode coverage is the main thing left

I guess this might actually be spicy since vixl sim only supports one round mode. might need to put them on the known failures list once created and only get fully tested with AVX128.

**Comment by lioncash** [comment]
This should be all good to go now

**Comment by alyssarosenzweig** [comment]
Looks good other than the thing Ryan mentioned. I can look into optimizing vcvtps2ph after this merges.

**Review by Sonicadvance1 — APPROVED** [review]
Nice nice nice nice

**Pull request merged**
