### PR TITLE
Fix reference to out of bounds address in offsetof

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Looks like the two std::array vectors can drop their fixed length count by one. 44 to 42.

`static constexpr std::array<uint64_t, 44> OffsetArrayAVX = {{`

Nice catch although.

**Comment by pmatos** [comment]
> Looks like the two std::array vectors can drop their fixed length count by one. 44 to 43.
> 
> `static constexpr std::array<uint64_t, 44> OffsetArrayAVX = {{`
> 
> Nice catch although.

Good point, thanks.

**Review by Sonicadvance1 — APPROVED** [review]

**Comment by pmatos** [comment]
Squashed - ready to merge.

**Comment by pmatos** [comment]
@Sonicadvance1 added the off-by-one printout fix to this patch.

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
