### PR TITLE
FEXCore: ARM64EC x64 entry/exit support 

### PR DESCRIPTION
**Pull request by bylaws**
This drops any need for frontend assembly code to be aware of FEX's SRA layout at the cost of the dispatcher needing to access the TEB. Also includes a patch to disable frontend callbacks during code compilation or block linking

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
This looks plausible... wondering if there's any expected perf change (positive or negative)?

**Comment by alyssarosenzweig** [comment]
> This drops any need for frontend assembly code to be aware of FEX's SRA layout

I suppose you have follow on patches that simplify the frontend? in isolation I'm not sure what the benefit of this PR is.

**Comment by bylaws** [comment]
The perf change here should be pretty much negligible, ec exit/entry isn't hot enough of a path for an extra instruction or two to realistically matter. This is a prerequisite for the frontend to make it upstream, rather than submitting it as a mix of fexcore changes and new code

**Comment by alyssarosenzweig** [comment]
> The perf change here should be pretty much negligible, ec exit/entry isn't hot enough of a path for an extra instruction or two to realistically matter. This is a prerequisite for the frontend to make it upstream, rather than submitting it as a mix of fexcore changes and new code

Sounds good. Ack from me on principle, will defer review to someone more knowledgable in this area.

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
