### PR TITLE
Remove Disabled_Tests file

### PR DESCRIPTION
**Pull request by pmatos**
It's exactly the same as Known_Failures.

### CODE REVIEW

**Comment by pmatos** [comment]
hummm, both 
```
The following tests FAILED:
	2273 - mcount_pic.c.gcc-target-test-64.jit.gcc-target-64 (Failed)
	2346 - pr57275.c.gcc-target-test-64.jit.gcc-target-64 (Failed)
``` 

were supposed to fail but actually pass now. Disabled_Tests was masking this.

**Comment by Sonicadvance1** [comment]
> hummm, both
> 
> ```
> The following tests FAILED:
> 	2273 - mcount_pic.c.gcc-target-test-64.jit.gcc-target-64 (Failed)
> 	2346 - pr57275.c.gcc-target-test-64.jit.gcc-target-64 (Failed)
> ```
> 
> were supposed to fail but actually pass now. Disabled_Tests was masking this.

Very fancy

**Comment by Sonicadvance1** [comment]
Oh yes, if one is related to SIGPROF then that should stay disabled because it's just a race condition, even if we're doing everything correctly.
AVX starting working makes sense.

**Comment by pmatos** [comment]
@Sonicadvance1 I did something here that makes total sense - in my head - but maybe I am missing context. I added the racy test to `Disabled_Tests` file and removed it from `Known_Failures`. Then I noticed it still fails. Looking at `guest_test_runner.py`, it seems that if a test is Disabled, it just gets the ResultCode -73 (what random number is this) and keeps going, i.e. since we expect a 0 ReturnCode by default. I added a commit to just 'skip' the test, i.e. we exit for a disabled test. WDYT?

**Comment by Sonicadvance1** [comment]
> @Sonicadvance1 I did something here that makes total sense - in my head - but maybe I am missing context. I added the racy test to `Disabled_Tests` file and removed it from `Known_Failures`. Then I noticed it still fails. Looking at `guest_test_runner.py`, it seems that if a test is Disabled, it just gets the ResultCode -73 (what random number is this) and keeps going, i.e. since we expect a 0 ReturnCode by default. I added a commit to just 'skip' the test, i.e. we exit for a disabled test. WDYT?

Yea, legacy weirdness that a disabled test just turns in to a "failing" test. Don't think about it too hard, your change makes sense, the original behaviour does not.

**Comment by pmatos** [comment]
> > @Sonicadvance1 I did something here that makes total sense - in my head - but maybe I am missing context. I added the racy test to `Disabled_Tests` file and removed it from `Known_Failures`. Then I noticed it still fails. Looking at `guest_test_runner.py`, it seems that if a test is Disabled, it just gets the ResultCode -73 (what random number is this) and keeps going, i.e. since we expect a 0 ReturnCode by default. I added a commit to just 'skip' the test, i.e. we exit for a disabled test. WDYT?
> 
> Yea, legacy weirdness that a disabled test just turns in to a "failing" test. Don't think about it too hard, your change makes sense, the original behaviour does not.

Thanks - ready to review then.

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
