### PR TITLE
ThunkLibs: Fix hostcall packer generation

### PR DESCRIPTION
**Pull request by skmp**
#### Overview

This fixes the generation of the hostcall packers, so we don't need to wrap thunks with C++ templates.

#### Depends
#1818

### CODE REVIEW

**Comment by neobrain** [comment]
I'm not convinced it's beneficial to rid of PackedArguments at the expense of moving more logic to the generator. The template is very lightweight, and my measurements indicated it doesn't contribute significantly to the compile time of large thunklibs like libGL.

IMO we should move towards minimizing logic in the generator. The struct-repacking branch gave me a bad feeling about how robust a code generator with lots of manual branching is, and the PackedArguments template is a good way to avoid that pitfall. I'd prefer shelving this PR for now until I've done more tinkering with the idea.

**Comment by skmp** [comment]
> I'm not convinced it's beneficial to rid of PackedArguments at the expense of moving more logic to the generator. The template is very lightweight, and my measurements indicated it doesn't contribute significantly to the compile time of large thunklibs like libGL.

The code was already there, the logic it wasn't moved. I just fixed the generation so it can be used. Before it was generated, broken, and we also had the PackedArguments.

> IMO we should move towards minimizing logic in the generator. The struct-repacking branch gave me a bad feeling about how robust a code generator with lots of manual branching is, and the PackedArguments template is a good way to avoid that pitfall. I'd prefer shelving this PR for now until I've done more tinkering with the idea.

I don't necessarily agree there. The `PackedArguments` template is a non-generalized huge thing, so it is obviously not a great solution either way.

Also, we can't use templates when doing cross bitness thunking, and evne for x86-64 / arm64 not all the packing rules are the same. We'll have to generate custom structs for everything for correctness, anyway.


Personally, I prefer codegeneration over templates for these things. Templates can be used where they are a good fit, like handling the conversions and stuff.

**Comment by Sonicadvance1** [comment]
"This fixes the generation of the hostcall packers" I don't understand what is being fixed here or why it is broken.

**Comment by skmp** [comment]
> "This fixes the generation of the hostcall packers" I don't understand what is being fixed here or why it is broken.

"so we don't need to wrap thunks with C++ templates."

**Comment by skmp** [comment]
As mentioned in a previous comment, the hostpackers were broken, and unused. I don't understand what is there to not understand here.

**Comment by neobrain** [comment]
FWIW https://github.com/FEX-Emu/FEX/pull/1868 adds a feature that makes the `_hostcall` symbols unnecessary and hence removes them entirely.

**Comment by Sonicadvance1** [comment]
Nothing changed on this so far.

**Comment by skmp** [comment]
> Nothing changed on this so far.

I've been blocked by lack of review/alternative proposals apart from "i don't like this / I don't think it is needed". Now, more time has to be wasted on rebases as well.

**Comment by skmp** [comment]
(Closing this as there is an ongoing powergrab by @Sonicadvance1, I will migrate my work to https://github.com/skmp/fex-emu-ng.git)

**Pull request closed without merging**
