### PR TITLE
ConstProp fixes for Darwinia

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Alongside #3666 This will fix Darwinia's Linux executable.

Two bugs here.
ConstProp with AddShift was transposing Base and Offset registers, which means we were scaling the Base and not scaling Offset.

Additionally we were accidentally allowing GPR loadstore limits on Vector loadstores which is invalid.

Both of these combined were causing fault behaviour in Darwinia after #3666 was fixed.

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
Looks you fixed 2 bugs, but the unit test only tests for 1 one of them. Do we need a second unit test covering the other case?

**Review by alyssarosenzweig — APPROVED** [review]

**Comment by Sonicadvance1** [comment]
> Looks you fixed 2 bugs, but the unit test only tests for 1 one of them. Do we need a second unit test covering the other case?

I'm not too terribly concerned about it, Seems like the confusion happened because we were returning a tuple and misunderstanding if the first or second OrderedNode* referred to base or offset. Now with a struct with named members it shouldn't occur, especially since I renamed the terrible `Arg0, Arg1` thing going on there.

**Comment by alyssarosenzweig** [comment]
> > Looks you fixed 2 bugs, but the unit test only tests for 1 one of them. Do we need a second unit test covering the other case?
> 
> I'm not too terribly concerned about it, Seems like the confusion happened because we were returning a tuple and misunderstanding if the first or second OrderedNode* referred to base or offset. Now with a struct with named members it shouldn't occur, especially since I renamed the terrible `Arg0, Arg1` thing going on there.

Yes, but if i'm going to rewrite all of this logic anyway, I'd like a way to test it that's more reliable than "does Darwinia crash?" 😉

**Comment by Sonicadvance1** [comment]
> > > Looks you fixed 2 bugs, but the unit test only tests for 1 one of them. Do we need a second unit test covering the other case?
> > 
> > 
> > I'm not too terribly concerned about it, Seems like the confusion happened because we were returning a tuple and misunderstanding if the first or second OrderedNode* referred to base or offset. Now with a struct with named members it shouldn't occur, especially since I renamed the terrible `Arg0, Arg1` thing going on there.
> 
> Yes, but if i'm going to rewrite all of this logic anyway, I'd like a way to test it that's more reliable than "does Darwinia crash?" 😉

I can do a unit test that tries to tell the difference between scaling on the wrong register once I've got a bit of time either later today or tomorrow

**Comment by Sonicadvance1** [comment]
> > > > Looks you fixed 2 bugs, but the unit test only tests for 1 one of them. Do we need a second unit test covering the other case?
> > > 
> > > 
> > > I'm not too terribly concerned about it, Seems like the confusion happened because we were returning a tuple and misunderstanding if the first or second OrderedNode* referred to base or offset. Now with a struct with named members it shouldn't occur, especially since I renamed the terrible `Arg0, Arg1` thing going on there.
> > 
> > 
> > Yes, but if i'm going to rewrite all of this logic anyway, I'd like a way to test it that's more reliable than "does Darwinia crash?" 😉
> 
> I can do a unit test that tries to tell the difference between scaling on the wrong register once I've got a bit of time either later today or tomorrow

Added a unit test that tests the multiple different optimizations that FEX does in the const-prop for SIB scaling. Should be relatively encompassing, if not all.

**Review by alyssarosenzweig — APPROVED** [review]
Awesome, thanks a ton

**Pull request merged**
