### PR TITLE
TestHarnessRunner: Use guest mapper for test harness files

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This will allow it to get picked up for named region handling. Thus ending up in the code caching for testing.

### CODE REVIEW

**Comment by skmp** [comment]
@Sonicadvance1 with the #1558 vma tracking and #1672 this is no longer required. I could split just the tracking features out if you want to have a quicker merge there

**Comment by Sonicadvance1** [comment]
The test harness files aren't actually getting mmap'd through FD so they wouldn't get tracked as a named region I don't believe?

**Comment by skmp** [comment]
All allocations done with `GuestMmap`/`GuestMunmap` will get tracked, even anonymous ones, though we'd have to change the aot notification logic there, as the callbacks only get called for fd that point files with names. 

Another option is switching to memfd for that code, that will get tracked, though there are naming issues there.

**Comment by Sonicadvance1** [comment]
We could also just open the test harness with an FD and mmap it so its file gets tracked appropriately. Rather than copying it to the final location.

**Comment by skmp** [comment]
> We could also just open the test harness file with an FD and mmap it so its file gets tracked appropriately. Rather than copying it to the final location.

That would be ideal

**Pull request merged**
