### PR TITLE
ARMEmitter: Fixes some warnings that cropped up.

### PR DESCRIPTION
**Pull request by Sonicadvance1**

### CODE REVIEW

**Comment by lioncash** [comment]
Oh, what warning pops up with these, so I can better avoid them if I add anything in the future?

**Comment by Sonicadvance1** [comment]
The warnings that cropped up on all of these was `__builtin_assume` expression had side effects which were being discarded. Will be visible on non-assertion builds.

**Comment by lioncash** [comment]
Oh huh, reducing it down to a minimal repro, it creates warnings even when the respective conversion functions are constexpr, but doesn't create any warnings when marked `[[gnu::const, gnu::pure]]`, odd

**Review by lioncash — APPROVED** [review]

**Comment by Sonicadvance1** [comment]
Weird. I had also poked at it and didn't find a solution. Not sure why the gnu options change behaviour.

**Pull request merged**
