### PR TITLE
WIP: Working PR for AVX128

### PR DESCRIPTION
**Pull request by Sonicadvance1**
This is the working branch for AVX128 and I'll be peeling off commits as other PRs get merged.

This is to allow visibility in to where the implementation is currently at to inform other PR reviews.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
`46% tests passed, 530 tests failed out of 986`

**Comment by Sonicadvance1** [comment]
`61% tests passed, 386 tests failed out of 986`

**Comment by alyssarosenzweig** [comment]
It looks like you want to define either a helper taking a lambda, or a macro, or maybe some template I wouldn't know how to get working, for:

```c
void AVXBinop(OpcodeArgs, HELPER) {
  const auto SrcSize = GetSrcSize(Op);
  const auto Is128Bit = SrcSize == Core::CPUState::XMM_SSE_REG_SIZE;

  auto Src1 = AVX128_LoadSource_WithOpSize(Op, Op->Src[0], Op->Flags, !Is128Bit);
  auto Src2 = AVX128_LoadSource_WithOpSize(Op, Op->Src[1], Op->Flags, !Is128Bit);

  RefPair Result {};

  Result.Low = HELPER(ElementSize, Src1.Low, Src2.Low);
  if (Is128Bit) {
    Result.High = LoadAndCacheNamedVectorConstant(OpSize::i128Bit, FEXCore::IR::NamedVectorConstant::NAMED_VECTOR_ZERO);
  } else {
    Result.High = HELPER(ElementSize, Src1.High, Src2.High);
  }

  AVX128_StoreResult_WithOpSize(Op, Op->Dest, Result);
}
```

Should let you deduplicate a *lot* of binops.

**Comment by alyssarosenzweig** [comment]
> Do you want to define either a helper taking a lambda, or a macro, or maybe some template I wouldn't know how to get working, for:
> 
> ```c
> void AVXBinop(OpcodeArgs, HELPER) {
>   const auto SrcSize = GetSrcSize(Op);
>   const auto Is128Bit = SrcSize == Core::CPUState::XMM_SSE_REG_SIZE;
> 
>   auto Src1 = AVX128_LoadSource_WithOpSize(Op, Op->Src[0], Op->Flags, !Is128Bit);
>   auto Src2 = AVX128_LoadSource_WithOpSize(Op, Op->Src[1], Op->Flags, !Is128Bit);
> 
>   RefPair Result {};
> 
>   Result.Low = HELPER(ElementSize, Src1.Low, Src2.Low);
>   if (Is128Bit) {
>     Result.High = LoadAndCacheNamedVectorConstant(OpSize::i128Bit, FEXCore::IR::NamedVectorConstant::NAMED_VECTOR_ZERO);
>   } else {
>     Result.High = HELPER(ElementSize, Src1.High, Src2.High);
>   }
> 
>   AVX128_StoreResult_WithOpSize(Op, Op->Dest, Result);
> }
> ```
> 
> Should let you deduplicate a _lot_ of binops.
> 
> Alternatively, can we implement VPUNPCKL, VPACKUS, etc with the usual VADD path? That would probably get most of the win with the least effort. But there's still a lot of boilerplate for implementations like VADDSUBP and VANDN.

Looks like the SVE-256 impls have an `ALUR` helper for reversed bin ops, used for VANDN. Seems like we'll want to do that for avx128 too

**Comment by Sonicadvance1** [comment]
> Do you want to define either a helper taking a lambda, or a macro, or maybe some template I wouldn't know how to get working, for:
> 
> ```c
> void AVXBinop(OpcodeArgs, HELPER) {
>   const auto SrcSize = GetSrcSize(Op);
>   const auto Is128Bit = SrcSize == Core::CPUState::XMM_SSE_REG_SIZE;
> 
>   auto Src1 = AVX128_LoadSource_WithOpSize(Op, Op->Src[0], Op->Flags, !Is128Bit);
>   auto Src2 = AVX128_LoadSource_WithOpSize(Op, Op->Src[1], Op->Flags, !Is128Bit);
> 
>   RefPair Result {};
> 
>   Result.Low = HELPER(ElementSize, Src1.Low, Src2.Low);
>   if (Is128Bit) {
>     Result.High = LoadAndCacheNamedVectorConstant(OpSize::i128Bit, FEXCore::IR::NamedVectorConstant::NAMED_VECTOR_ZERO);
>   } else {
>     Result.High = HELPER(ElementSize, Src1.High, Src2.High);
>   }
> 
>   AVX128_StoreResult_WithOpSize(Op, Op->Dest, Result);
> }
> ```
> 
> Should let you deduplicate a _lot_ of binops.
> 
> Alternatively, can we implement VPUNPCKL, VPACKUS, etc with the usual VADD path? That would probably get most of the win with the least effort. But there's still a lot of boilerplate for implementations like VADDSUBP and VANDN.

Did it. Lots of duplication removed.

**Comment by alyssarosenzweig** [comment]
Looks great!

**Comment by Sonicadvance1** [comment]
`65% tests passed, 344 tests failed out of 986`
66 more handlers to be implemented still.
Slowing down a bit since I'm now hitting the more complex instruction implementations.

**Comment by Sonicadvance1** [comment]
`85% tests passed, 152 tests failed out of 986`
11 more handlers to implement.

**Comment by alyssarosenzweig** [comment]
Now that everything is fanned out into PRs, closing this one

**Pull request closed without merging**
