### PR TITLE
Github: Adds mingw build test workflow

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Currently only does a build, doing a CI run means figuring out why TestHarnessRunner doesn't find libraries correctly.

I want to ensure we don't break building at least while sorting out the rest of this.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
`buildbot-macmini-2` has been removed from mingw supporting status for now. Something is wrong with it seemingly due to running Ubuntu 20.04

**Comment by Sonicadvance1** [comment]
Turns out this is an outdated cmake version issue.
macmini-2 has cmake version: `cmake version 3.16.3`
macmini-1 has cmake version: `cmake version 3.22.1`
Bisecting to figure out what we need to bump the minimum up to...

**Comment by Sonicadvance1** [comment]
Couldn't reproduce locally by using 3.16.3, maybe Canonical had some patches on top of that version or something.
Just updated the macmini-2 runner's cmake version which resolved this issue.
Reenabled as a mingw runner.

**Comment by Sonicadvance1** [comment]
Rebased to make sure this was still working for the merge.

**Review by lioncash — APPROVED** [review]

**Pull request merged**
