### PR TITLE
VAES support

### PR DESCRIPTION
**Pull request by Sonicadvance1**
Not directly related to AVX128 but we will be gaining support for VAES through it, so good to add tests before the rest.

1. Implement support for querying VAES through HostFeatures
2. Add unittests for the four new instructions
3. Expose the feature in CPUID if supported

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
@pmatos Looks like the code formatting script isn't properly ignoring python files. This PR will need to ignore the code formatting failure until that gets resolved.

**Comment by pmatos** [comment]
> @pmatos Looks like the code formatting script isn't properly ignoring python files. This PR will need to ignore the code formatting failure until that gets resolved.

I will get to it today.

**Review by alyssarosenzweig — APPROVED** [review]
cute lil extension 👍

**Comment by pmatos** [comment]
> > @pmatos Looks like the code formatting script isn't properly ignoring python files. This PR will need to ignore the code formatting failure until that gets resolved.
> 
> I will get to it today.

@Sonicadvance1 fixed #3728

**Pull request merged**
