### PR TITLE
clang-format: left-align escaped newlines

### PR DESCRIPTION
**Pull request by alyssarosenzweig**
alternative to #3638. this is theoretically better for side-by-side diffs. in practice it may make other diffs worse since all the \'s change when part of the macro change.

### CODE REVIEW

**Review by Sonicadvance1 — APPROVED** [review]

**Comment by neobrain** [comment]
> in practice it may make other diffs worse since all the 's change when part of the macro change.

This is a good point. I'm actually inclined to give this a `-0` for that reason, but I ultimately care more that long code blocks for which that is a problem shouldn't need to be macros in the first place.

**Comment by Sonicadvance1** [comment]
I fully support this since the spacing change is trivial. It's also a good enough reference that if anyone were to actually care about changing defines to something that isn't a define then they can walk through each individual formatting change in future PRs.

**Comment by neobrain** [comment]
> I fully support this since the spacing change is trivial. It's also a good enough reference that if anyone were to actually care enough about changing defines to something that isn't a define then they can walk through each individual formatting change in future PRs.

Yes, to clarify my `-0` is only a formal note, not an objection to merging the change.

**Comment by Sonicadvance1** [comment]
I'll formally click the merge button since it's trivial then.

**Pull request merged**
