### PR TITLE
x87StackOptimizationPass: Default initialise StackMemberInfo members

### PR DESCRIPTION
**Pull request by bylaws**
Not doing so is UB.

### CODE REVIEW

**Review by neobrain — APPROVED** [review]
`std::optional` doesn't need the initializer since it does have a default constructor, but LGTM.

**Review by Sonicadvance1 — APPROVED** [review]

**Comment by pmatos** [comment]
This PR looks like a nonfunctional change. Although you refactored the constructor, the behavior didn't change. You moved the initial values to the member declaration, but they were being initialized anyway in the constructor.

Unless the point here is that default initializing `InterpretAsFloat` to false applies to other constructors, the only member from our Discord chat lacking a default constructor. Another strange thing that I should point out is that UBSan doesn't flag this as UB.

**Comment by pmatos** [comment]
> This PR looks like a nonfunctional change. Although you refactored the constructor, the behavior didn't change. You moved the initial values to the member declaration, but they were being initialized anyway in the constructor.
> 
> Unless the point here is that default initializing `InterpretAsFloat` to false applies to other constructors, the only member from our Discord chat lacking a default constructor. Another strange thing that I should point out is that UBSan doesn't flag this as UB.

OK - after some further look, the impact here is on `StackMemberInfo() {},` and initializing `InterpretAsFloat,` which, as a fundamental type, doesn't have a default constructor. Also, UBsan probably won't show this because it would be a read on an uninitialized member, so that it would be MSan instead. Sorry, this comment is just meant to clarify my understanding. The PR looks good to me. 

I am still curious about how often this default constructor is called, but I will do a more thorough investigation after this lands.

**Comment by bylaws** [comment]
Ref is also just a pointer so that also needs initializing, it's called in clear()

**Pull request merged**
