### PR TITLE
Set tag properly in X87 FST(reg)

### PR DESCRIPTION
**Pull request by pmatos**
Currently its not being set and attached test fails.

### CODE REVIEW

**Comment by pmatos** [comment]
Apologies for pessimization - my current work on x87 will sort this out.

**Comment by alyssarosenzweig** [comment]
Please split changes into appropriate commits for ease of review. This PR  should probably 3 commits:

1. fix the bug
2. add the tests
3.  update instcountci

Thanks!

**Comment by pmatos** [comment]
> Please split changes into appropriate commits for ease of review. This PR should probably 3 commits:
> 
> 1. fix the bug
> 2. add the tests
> 3. update instcountci
> 
> Thanks!

That makes total sense. Let me do that splitting for all my PRs. :)

**Comment by pmatos** [comment]
> Please split changes into appropriate commits for ease of review. This PR should probably 3 commits:
> 
> 1. fix the bug
> 2. add the tests
> 3. update instcountci
> 
> Thanks!

and... done.

**Comment by alyssarosenzweig** [comment]
It looks like your instcountci changes are stale / from another PR. Drop the commit and run `instcountci` to refresh:

```
alyssa@blossom ~/bin (main)> cat instcountci 
set -e
ninja
ninja instcountci_tests || true
ninja instcountci_update_tests
git commit -sam "InstCountCI: Update"
```

**Comment by pmatos** [comment]
> It looks like your instcountci changes are stale / from another PR. Drop the commit and run `instcountci` to refresh:
> 
> ```
> alyssa@blossom ~/bin (main)> cat instcountci 
> set -e
> ninja
> ninja instcountci_tests || true
> ninja instcountci_update_tests
> git commit -sam "InstCountCI: Update"
> ```

Updated.

**Review by Sonicadvance1 — APPROVED** [review]
A shame about the performance hit but I can see why this is necessary.

**Pull request merged**
