### PR TITLE
Cleanup syscalls headers

### PR DESCRIPTION
**Pull request by neobrain**
No interface changes, just throwing out unused code and shortening implementations.

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Just to confirm, this was tested with `// #define DEBUG_STRACE` uncommented in Syscalls.h right?

**Comment by neobrain** [comment]
> Just to confirm, this was tested with `// #define DEBUG_STRACE` uncommented in Syscalls.h right?

Yup. Tested running Ender Lilies, which still shows well-formatted debug messages like
```
[DEBUG] newfstatat(-100, /Build/++UE4/Sync/Engine/Binaries/ThirdParty/PhysX3/Linux/x86_64-unknown-linux-gnu/tls/x86_64, 0x7fffffffcd37, 0) = -2
```

**Review by Sonicadvance1 — APPROVED** [review]
TIL about `operator+` on lambdas and I love it!

**Comment by skmp** [comment]
Hmm, this removes the inner impl warping structs from the registered lambdas, which means we won't get backtraces with the syscall name though. Was that intended?

**Pull request merged**
