### PR TITLE
Fix 8/16-bit ADC/SBC

### PR DESCRIPTION
**Pull request by alyssarosenzweig**
alternative to #3600

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Interestingly, while this solves the unittest, it doesn't solve the rendering issue that FF7 is encountering.

**Comment by alyssarosenzweig** [comment]
> Interestingly, while this solves the unittest, it doesn't solve the rendering issue that FF7 is encountering.

Curious. Guess we're going to want a second unit test too, lest we optimize this later 😅 

Racking my brain for what behaviour change could possibly happen here.

**Comment by alyssarosenzweig** [comment]
Hey, if it's good enough for me to repro, that'll do! thanks 😸

**Comment by alyssarosenzweig** [comment]
Oh, derp, I know what this is. Fix coming. thanks!

**Comment by Sonicadvance1** [comment]
With the latest changes FF7 now renders correctly again!

**Review by Sonicadvance1 — APPROVED** [review]
Nice little optimization and nice bug fix!

**Pull request merged**
