### PR TITLE
OpcodeDecoder: Shorten up GPR and MM base offset retrieval

### PR DESCRIPTION
**Pull request by lioncash**
Previously, getting the offset of a register involved a long string of code via offsetof to get. We can wrap these behind two helper functions to make writing code that requires offsets a little more convenient

### CODE REVIEW

**Comment by Sonicadvance1** [comment]
Do these helpers get inlined everywhere even with the one's that don't have the implementation body visible outside of OpcodeDispatcher?

**Comment by lioncash** [comment]
we compile with LTO, so I'd imagine so. I can move them into the header if that's a concern though

**Comment by Sonicadvance1** [comment]
Would be nice for them to be in the header to enforce intent here.

**Comment by lioncash** [comment]
Done

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
