### PR TITLE
unittests: Add test thunk library

### PR DESCRIPTION
**Pull request by neobrain**
This adds a new FEXLinuxTest written against a custom `libfex_thunk_test` library. `libfex_thunk_test` allows us to define interfaces specifically to trigger thunk generator edge cases that couldn't easily be tested for in actual libraries.

The new test opens a third category of thunk-related tests:
* unittests/ThunkLibs: Unit tests that check the syntax tree of `thunkgen` code output and (in the future) results of data layout analysis (no runtime behavior is checked)
* unittests/ThunkFunctionalTests: Integration tests that runs simple applications (e.g. glxinfo) to verify basic functionality of real-world libraries works
* FEXLinuxTests/thunk_testlib: Mixed unit/integration tests that benefit from us controlling the interfaces in `libfex_thunk_test`. Individual properties of the thunk generator can be checked by co-designing tests and the tested thunk to trigger problematic edge-cases easily.

Ideally the new library and the test should only be enabled if both `BUILD_THUNKS` and `BUILD_FEX_LINUX_TESTS` are set. However, forwarding these settings through our various `ExternalProject`s would be overly complicated. Instead, the new library is always built if `BUILD_THUNKS` is on, and the new test is always built if `BUILD_FEX_LINUX_TESTS` is on (but excluded from the `fex_linux_tests` umbrella target unless `BUILD_THUNKS` is enabled). Since building these targets doesn't do any harm either way, this is a reasonable middle ground.

TODO:
- [x] The tests fail unless thunking of `libfex_thunk_test` is enabled. Should we force-enable thunking of this library in FEX, or is it sufficient to enable it in CI?
    - Resolved: The test targets now pass the `-k` switch to FEXLoader to enable thunking of the test library

### CODE REVIEW

**Comment by neobrain** [comment]
@Sonicadvance1 This requires thunks to be built (`BUILD_THUNKS=ON`), installed (`ninja install`), and enabled (in `thunks.json`) for testing to work properly. Is our CI set up for this already, or will this need some adjustments?

**Comment by Sonicadvance1** [comment]
> @Sonicadvance1 This requires thunks to be built (`BUILD_THUNKS=ON`), installed (`ninja install`), and enabled (in `thunks.json`) for testing to work properly. Is our CI set up for this already, or will this need some adjustments?

Thunks are built and installed on all the runners: https://github.com/FEX-Emu/FEX/blob/main/.github/workflows/ccpp.yml#L76

Thunks themselves are only tested on the x86 runner none of the ARM runners has a GPU in it: https://github.com/FEX-Emu/FEX/blob/main/.github/workflows/ccpp.yml#L234

**Comment by neobrain** [comment]
Thunking of the new `libfex_thunk_test` is now always enabled for FEXLinuxTests. This is implemented by passing the `-k` flag when invoking FEXLoader for these tests, similar to how it's done in the ThunkFunctionalTests.

**Comment by neobrain** [comment]
CI is failing on what looks like pre-existing flakes. The actual changes in this PR are good to go.

**Comment by neobrain** [comment]
There we go, now truly passing CI.

> Thunking of the new libfex_thunk_test is now always enabled for FEXLinuxTests. This is implemented by passing the -k flag when invoking FEXLoader for these tests, similar to how it's done in the ThunkFunctionalTests.

This behavior is now only enabled for the thunk test, and only if building thunks are enabled *and* if glibc allocator hooking is disabled.

**Review by Sonicadvance1 — APPROVED** [review]

**Pull request merged**
