### PR TITLE
Jitarm64: Implements spin-loop futex for JIT blocks 

### PR DESCRIPTION
**Pull request by Sonicadvance1**
~~Needs #3339 merged first.~~

This will ensure that multiple concurrent SIGBUS handlers in the same
code block doesn't modify the same code.

### CODE REVIEW

**Comment by bylaws** [comment]
I feel like FutexSpinWait probably isn't the best name for this, I haven't see futex used to refer to anything but the Linux syscall, which this explicitly doesn't use

**Comment by Sonicadvance1** [comment]
> I feel like FutexSpinWait probably isn't the best name for this, I haven't see futex used to refer to anything but the Linux syscall, which this explicitly doesn't use

Renamed to SpinWaitLock

**Comment by alyssarosenzweig** [comment]
There's nothing appropriate in the stl? or provided by Linux? Why do we need to roll our own?

**Comment by Sonicadvance1** [comment]
> There's nothing appropriate in the stl? or provided by Linux? Why do we need to roll our own?

Nothing in the STL, libc, or Linux similar to a spin-loop.
Closest things end up being `std::condition_variable` or `pthread_cond_t`, or a kernel futex. All of these are too heavy for what is getting accomplished here, which is a spin-loop/spin-lock.

**Review by lioncash — APPROVED** [review]

**Pull request merged**
